# Generated by Django 5.0.3 on 2024-03-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_platform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerbill",
            name="payed_value",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name="PlayerVisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_day", models.DateTimeField()),
                (
                    "payed_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="app_platform.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
