# Generated by Django 5.0.3 on 2024-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
