# Generated by Django 5.0.3 on 2024-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
