# Generated by Django 5.0.3 on 2024-04-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_birth_date_player_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerBill',
            new_name='PlayerBills',
        ),
    ]
