# Generated by Django 5.0.3 on 2024-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_playerbill_playerbills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbills',
            name='payed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
